/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    achievements: Achievement;
    konten: Konten;
    pengurus: Pengurus;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    konten: KontenSelect<false> | KontenSelect<true>;
    pengurus: PengurusSelect<false> | PengurusSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * ID identitas absolut dari sistem Google OAuth.
   */
  googleId?: string | null;
  authProvider?: ('local' | 'google')[] | null;
  role: 'superadmin' | 'admin' | 'athlete';
  namaLengkap: string;
  /**
   * Referensi ke koleksi media untuk foto profil atlet.
   */
  fotoProfil?: (number | null) | Media;
  tempatLahir?: string | null;
  tanggalLahir?: string | null;
  jenisKelamin?: ('Laki-laki' | 'Perempuan') | null;
  nomorTelepon?: string | null;
  sabuk?:
    | (
        | 'Putih'
        | 'Kuning'
        | 'Hijau'
        | 'Biru'
        | 'Coklat Kyu 1'
        | 'Coklat Kyu 2'
        | 'Coklat Kyu 3'
        | 'Hitam Dan 1'
        | 'Hitam Dan 2'
        | 'Hitam Dan 3'
        | 'Hitam Dan 4'
        | 'Hitam Dan 5'
      )
    | null;
  totalPoin?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  owner: number | User;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  atlet: number | User;
  namaKejuaraan: string;
  kategori: string;
  jenisKejuaraan: 'Open' | 'Festival';
  peringkat: 'Juara 1' | 'Juara 2' | 'Juara 3';
  tingkatKejuaraan: 'Kecamatan' | 'Kabupaten/Kota' | 'Provinsi' | 'Nasional' | 'Internasional';
  tanggalKejuaraan: string;
  lokasiKejuaraan?: string | null;
  sertifikat: number | Media;
  status?: ('pending' | 'approved' | 'rejected') | null;
  catatanPenolakan?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "konten".
 */
export interface Konten {
  id: number;
  judul: string;
  /**
   * Muncul sebagai deskripsi singkat di card UI.
   */
  ringkasan: string;
  kategori: 'Kegiatan' | 'Kejuaraan' | 'Ujian' | 'Pelatihan' | 'Pengumuman' | 'Berita' | 'Lainnya';
  /**
   * Tanggal mulai pelaksanaan kegiatan.
   */
  tanggalMulai?: string | null;
  /**
   * Kosongkan jika kegiatan hanya satu hari.
   */
  tanggalSelesai?: string | null;
  /**
   * Otomatis diisi saat status dipublikasikan.
   */
  publishedAt?: string | null;
  /**
   * Contoh: GOR Amongrogo
   */
  lokasi?: string | null;
  thumbnail: number | Media;
  isiKonten: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pengurus".
 */
export interface Pengurus {
  id: number;
  /**
   * Pilih jika pengurus merupakan Atlet terdaftar. Nama & Foto akan terisi otomatis jika dikosongkan.
   */
  atlet?: (number | null) | User;
  /**
   * Biarkan kosong jika ingin mengambil nama otomatis dari akun Atlet di atas.
   */
  nama?: string | null;
  divisi: 'Pengurus Inti' | 'Divisi Latihan' | 'Divisi Humas' | 'Divisi KRT/UU';
  jabatan: 'Ketua' | 'Sekretaris' | 'Bendahara 1' | 'Bendahara 2' | 'Bendahara 3' | 'Koor' | 'Staf';
  jurusan: string;
  /**
   * Biarkan kosong jika ingin mengambil foto profil dari akun Atlet di atas.
   */
  foto: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'konten';
        value: number | Konten;
      } | null)
    | ({
        relationTo: 'pengurus';
        value: number | Pengurus;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  googleId?: T;
  authProvider?: T;
  role?: T;
  namaLengkap?: T;
  fotoProfil?: T;
  tempatLahir?: T;
  tanggalLahir?: T;
  jenisKelamin?: T;
  nomorTelepon?: T;
  sabuk?: T;
  totalPoin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  owner?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  atlet?: T;
  namaKejuaraan?: T;
  kategori?: T;
  jenisKejuaraan?: T;
  peringkat?: T;
  tingkatKejuaraan?: T;
  tanggalKejuaraan?: T;
  lokasiKejuaraan?: T;
  sertifikat?: T;
  status?: T;
  catatanPenolakan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "konten_select".
 */
export interface KontenSelect<T extends boolean = true> {
  judul?: T;
  ringkasan?: T;
  kategori?: T;
  tanggalMulai?: T;
  tanggalSelesai?: T;
  publishedAt?: T;
  lokasi?: T;
  thumbnail?: T;
  isiKonten?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pengurus_select".
 */
export interface PengurusSelect<T extends boolean = true> {
  atlet?: T;
  nama?: T;
  divisi?: T;
  jabatan?: T;
  jurusan?: T;
  foto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}